from datetime import datetime
from typing import Annotated

from bson import ObjectId
from pydantic import BaseModel, BeforeValidator, ConfigDict, Field

PyObjectID = Annotated[ObjectId, BeforeValidator(ObjectId)]


class Stats(BaseModel):
    """Upgradeable Stats for all characters"""

    MAX_HP: int = Field(description="Maximum Health", alias="health")
    ATK: int = Field(description="Attack Power", alias="attack")
    DEF: int = Field(description="Defense", alias="defense")
    SPD: int = Field(description="Speed", alias="speed")
    EVA: int = Field(description="Evasion", alias="evasion")


class Hero(BaseModel):
    """Collectable Characters owned and controlled by Players"""

    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    id: PyObjectID | None = Field(
        alias="_id",
        default=None,
        description="The Hero's unique ID, auto-generated by MongoDB on creation",
    )
    owner_id: str | None = Field(
        description="The discord (snowflake) id of the player who owns this hero"
    )
    name: str
    level: int
    HP: int = Field(alias="current_health")
    stats: Stats
    avatar_url: str | None = Field(
        default=None,
        description="The url to hero's avatar image. Used in Embeds and Combat",
    )
    created_at: datetime
