from bson import ObjectId
from datetime import datetime
from pydantic import BaseModel, Field, BeforeValidator, ConfigDict
from typing import Annotated

PyObjectID = Annotated[ObjectId, BeforeValidator(lambda v: ObjectId(v))]

class Stats(BaseModel):
    MAX_HP: int = Field(description="Maximum Health")
    ATK: int = Field(description="Attack Power")
    DEF: int = Field(description="Defense")
    SPD: int = Field(description="Speed")
    EVA: int = Field(description="Evasion")
    
class Hero(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)
    
    id: PyObjectID | None = Field(alias='_id', default=None, description="The Hero's unique ID, auto-generated by MongoDB on creation")
    owner_id: str | None = Field(description='The discord (snowflake) id of the player who owns this hero')
    name: str
    level: int
    HP: int
    stats: Stats
    createdAt: datetime
    